### ISSUE TITLE
why can't I change the similarity in CF user-user recommender ?

### ISSUE THREAD

**Issue by ChemsEddineBerbegue** [lenskit/lkpy#106]
similarity matrix parameter is available only in item-item, why can't see the same parameter with user-user as presented in the documentation ?

**Comment by mdekstrand** [comment]
For efficiency reasons, neither of LKPY's k-NN recommenders allow the similarity function to be reconfigured. They compute cosine similarities because they generally perform better than other similarity functions and can be efficiently computed with sparse matrix operations.

The item-item algorithm _exposes_ the computed similarity matrix as the `similarity_matrix_` attribute, and you can reuse much of item-item's logic by overriding `fit` to change how this matrix is computed. User-user does not precompute similarities, so there is no similarity matrix to expose.
