### ISSUE TITLE
Nested parallelism overloading threads pool

### ISSUE THREAD

**Issue by david-cortes** [lenskit/lkpy#257]
The `lu` solver for `BiasedMF` runs into nested parallelism which slows it down considerably. It would run a lot faster if the number of threads for BLAS and LAPACK were limited to 1. Example:
```python
import numpy as np, pandas as pd
from lenskit.algorithms.als import BiasedMF

nusers = int(1e3)
nitems = int(1e3)
nnz = int(1e5)
np.random.seed(1)
df = pd.DataFrame({
    "user" : np.random.randint(nusers, size=nnz),
    "item" : np.random.randint(nitems, size=nnz),
    "rating" : np.random.gamma(1,1, size=nnz)
})

model = BiasedMF(50, iterations=3, reg=0.05,
                 rng_spec=np.random.RandomState(seed=1),
                 damping=5, bias=True, method='lu')
```
```
%%time
model.fit(df)
```
```python
from threadpoolctl import threadpool_limits
model = BiasedMF(50, iterations=3, reg=0.05,
                 rng_spec=np.random.RandomState(seed=1),
                 damping=5, bias=True, method='lu')
```
```python
%%time
with threadpool_limits(limits=1, user_api='blas'):
    model.fit(df)
```

When using OpenBLAS (pthreads variant), I get the following timings:
* First version: `CPU times: user 1min 13s, sys: 4min 2s, total: 5min 16s, Wall time: 24.7 s`
* Second version: `CPU times: user 935 ms, sys: 1.06 s, total: 1.99 s, Wall time: 157 ms`

With MKL:
* First version: `CPU times: user 7.08 s, sys: 5.74 s, total: 12.8 s, Wall time: 3.72 s`
* Second version: `CPU times: user 558 ms, sys: 72.9 ms, total: 630 ms, Wall time: 130 ms`

**Comment by mdekstrand** [comment]
Thank you for bringing this up. This is a problem that I am aware of, and am working on documentation and diagnostics for the next LensKit release. We already have some performance tips (https://lkpy.readthedocs.io/en/latest/performance.html), and have started on diagnostic functions that will emit warnings at an appropriate point if LensKit detects that you are likely in an oversubscription situation, coupled with documentation on how to fix each of them. Since there are so many variations in runtime environments, I'm hesitant to put code in LensKit to automatically try to control everything.

The highest-performance setup I know of for these particular algorithms is to use TBB for both MKL and Numba. Then you do not need to restrict MKL's threading - TBB will use a single thread pool across both Numba and MKL, and there is no oversubscription.  Oversubscription typically arises when one or both is using OpenMP.
