### ISSUE TITLE
Add default recommendation capabilities

### ISSUE THREAD

**Issue by mdekstrand** [lenskit/lkpy#50]
Right now, the recommend APIs don't have any default candidate sets. Make one.

**Comment by mdekstrand** [comment]
Possible design:

* `TopNRecommender` takes two subcomponents: a `Predictor`, and a `CandidateSelector`.
* Everything gets trained with `fit`.

```
pred = BiasedMFPredictor(50)
rec = TopNRecommender(pred, selector=UnratedItems())
rec.fit(ratings)
```

`recommend` can automatically wrap a predictor in a top-N recommender.

### Problem cases:

* The predictor is already fit - how do we fit the recommender & candidate selector
* A little more manual structure

### Other Concerns

* Embedding recommendation into every algorithm results in error-prone boilerplate for implementing algorithms

**Comment by mdekstrand** [comment]
@rburke2233 would love if you have any input here.

**Comment by rburke2233** [comment]
It is probably enough to have a small set of parameterizable functions with the signature CS(u,i) -> {i} that are input to the evaluation process. For algorithms that are list-wise, I guess you would need the selection function in the fitting process, but that seems like a special case to me, not generally enough to embed in the API. BPR, for example, has a specific way of sampling unrated items, so that seems to be part of the algorithm rather than a configurable component.
